name: Build HDWrt

on:
  workflow_dispatch:  # 手动触发
  push:
    paths:
      - '.config'     # 当.config文件变更时自动触发
  #schedule:
  #  - cron: '0 0 * * *'  # 每天UTC 0点自动编译（北京时间8点）

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 最长6小时

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up environment
        run: |
          #sudo apt-get update
          #sudo apt-get install -y build-essential libncurses5-dev
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget parted libparted-dev qemu-utils

      - name: Initialize OpenWrt
        env:
          REPO_URL: https://github.com/rememberlostcode/openwrt.git  # 替换为你的仓库
          REPO_BRANCH: v24.10.0
        run: |
          git clone --depth=1 $REPO_URL -b $REPO_BRANCH hdwrt
          cd hdwrt
          git branch
          
      - name: Update feeds and apply config
        run: |
          cd hdwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds install -a
          cat .config | grep parted
          cat .config | grep luci
          cat .config | grep PREINIT
          git checkout .config

      - name: Customize via SSH (可选)
        if: ${{ env.SSH_ACTIONS == 'true' }}
        uses: mxschmitt/action-tmate@v3.19
        env:
          SSH_ACTIONS: false  # 设为true启用SSH调试

      - name: Compile OpenWrt
        run: |
          cd hdwrt
          make -j$(nproc) V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.1
        with:
          name: hdwrt-binaries
          path: hdwrt/bin/targets/*
